import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

export default function Home() {
  return (
      <>
        <Head>
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap');
        </style> 
          <title>AENIMA APP</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="index">
          <div className="imageIndex">
            <Image src="/Assets/logo/logo.png" alt="logo" width={150} height={150}></Image>
          </div>
          <div className="textIndex">
            <h1>PROTOTIPO</h1>
          </div>
          <div className="buttonsIndex">
            <Link href="/desktop">
              <p className="boton">DESKTOP</p>
            </Link>
            <Link href="/mobile">
              <p className="boton">MOBILE</p>
            </Link>
          </div>           
        </div>
      </>
  )
}
