import Head from 'next/head'
import BannerMobile from '../components/Banner/BannerMobile'
import Blog from '../components/Blog/Blog'
import Footer from '../components/Footer/Footer'
import HeaderMobile from '../components/Header/HeaderMobile'
import Tendencias from '../components/Tendencias/Tendencias'

export default function Home() {
  return (
      <>
        <Head>
          <title>AENIMA APP</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="container-mobile">
          <HeaderMobile/>
          <BannerMobile/>
          <Tendencias/>
          <Blog/>
          <Footer/>
        </div>
      </>
  )
}
