import Head from 'next/head'
import Banner from '../components/Banner/Banner'
import Header from '../components/Header/Header'

export default function Home() {
  return (
      <>
        <Head>
          <title>AENIMA APP</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="container-mobile">
          <Header/>
          <Banner/>
        </div>
      </>
  )
}
